version: '3'

services:
  chatbot_api:
    build:
      context: ./chatbot_api
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - ./chroma_db:/app/chroma_db/
      - ./data:/app/data

  chatbot_frontend:
    build:
      context: ./chatbot_frontend
    env_file:
      - .env
    depends_on:
      - chatbot_api
    ports:
      - "8501:8501"